# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/72774/Documents/JITRAVELLING/Fall2018/VE370/VE370_Project/Project_Two/P2_pipeline/P2_pipeline.cache/wt [current_project]
set_property parent.project_path C:/Users/72774/Documents/JITRAVELLING/Fall2018/VE370/VE370_Project/Project_Two/P2_pipeline/P2_pipeline.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/72774/Documents/JITRAVELLING/Fall2018/VE370/VE370_Project/Project_Two/P2_pipeline/P2_pipeline.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  C:/Users/72774/Documents/JITRAVELLING/Fall2018/VE370/VE370_Project/Project_Two/Pipeline/ALU.v
  C:/Users/72774/Documents/JITRAVELLING/Fall2018/VE370/VE370_Project/Project_Two/Pipeline/ALU_control.v
  C:/Users/72774/Documents/JITRAVELLING/Fall2018/VE370/VE370_Project/Project_Two/Pipeline/clock_for_simulation.v
  C:/Users/72774/Documents/JITRAVELLING/Fall2018/VE370/VE370_Project/Project_Two/Pipeline/control.v
  C:/Users/72774/Documents/JITRAVELLING/Fall2018/VE370/VE370_Project/Project_Two/Pipeline/data_memory.v
  C:/Users/72774/Documents/JITRAVELLING/Fall2018/VE370/VE370_Project/Project_Two/Pipeline/forwarding_unit_1.v
  C:/Users/72774/Documents/JITRAVELLING/Fall2018/VE370/VE370_Project/Project_Two/Pipeline/instruction_memory.v
  C:/Users/72774/Documents/JITRAVELLING/Fall2018/VE370/VE370_Project/Project_Two/Pipeline/pc.v
  C:/Users/72774/Documents/JITRAVELLING/Fall2018/VE370/VE370_Project/Project_Two/Pipeline/state_register.v
  C:/Users/72774/Documents/JITRAVELLING/Fall2018/VE370/VE370_Project/Project_Two/Pipeline/sign_extension.v
  C:/Users/72774/Documents/JITRAVELLING/Fall2018/VE370/VE370_Project/Project_Two/Pipeline/register.v
  C:/Users/72774/Documents/JITRAVELLING/Fall2018/VE370/VE370_Project/Project_Two/Pipeline/Mux_N_bit.v
  C:/Users/72774/Documents/JITRAVELLING/Fall2018/VE370/VE370_Project/Project_Two/Pipeline/pipeline.v
  C:/Users/72774/Documents/JITRAVELLING/Fall2018/VE370/VE370_Project/Project_Two/Pipeline/board.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top Main_Unit -part xc7a35tcpg236-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Main_Unit.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file Main_Unit_utilization_synth.rpt -pb Main_Unit_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
